# Imports

In [7]:
from transformers import EfficientNetForImageClassification
import pandas as pd
from datasets import load_dataset, Dataset, DatasetDict, Audio, ClassLabel, Sequence
from glob import glob 
from pydub import AudioSegment
import os
from tqdm.auto import tqdm
import requests
import json
import time
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from opensoundscape.annotations import BoxedAnnotations

# Dataset Class Exploration

In [8]:
# load model 
model = EfficientNetForImageClassification.from_pretrained(
    "DBD-research-group/EfficientNet-B1-BirdSet-XCL",
    num_channels=1,
    # cache_dir=CACHE_DIR,
    ignore_mismatched_sizes=True,
)

# get model classes
model_labels = list(model.config.id2label.values())

# load conversion from ebird codes to scientific names
ebird_df = pd.read_excel("/home/gil/comp0173/Clements_v2025-October-2025.xlsx", usecols=[1,7], index_col=1)

# get dataset classes
dataset_df = pd.read_csv("/home/gil/comp0173/BirdSet/data/DataS1/annotations_details.csv")
dataset_labels = pd.unique(dataset_df.loc[:,"scientific_name"])

/home/gil/miniconda3/envs/comp0173-opso/lib/python3.10/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [9]:
# convert scientific name to ebird code
dataset_classes = []

for label in dataset_labels:
    try:
        dataset_classes.append(ebird_df.loc[label,"species_code"])
    except:
        print(f"{label} not found")

# identify classes present in the dataset AND in the model
TARGET_CLASSES = list(set(dataset_classes).intersection(set(model_labels)))

# Refactor dataset into HF datasets format

In [10]:
dataset_root = "/home/gil/comp0173/BirdSet/data/DataS1"

## Train

### Download files
See `extract_xcl_train_ogg_debug.py` for downloading the dataset

In [ ]:
df_all = pd.read_parquet("/home/gil/comp0173/BirdSet/data/DataS1_DT_train/ogg/metadata-full.parquet")
failed = [443298, 842661, 282934, 497924, 769107, 600216, 769104, 629813, 267870, 509691, 722620]

missing = df_all[~df_all["filepath"].map(lambda p: os.path.exists(p))]
print("Missing:", len(missing))
print(missing[["filepath"]].head())

available = df_all[df_all["filepath"].map(lambda p: os.path.exists(p))]
available.to_parquet("/home/gil/comp0173/BirdSet/data/DataS1_DT_train/metadata-train.parquet")

Missing: 11
                                                 filepath
id
722620  /home/gil/comp0173/BirdSet/data/DataS1_DT_trai...
267870  /home/gil/comp0173/BirdSet/data/DataS1_DT_trai...
509691  /home/gil/comp0173/BirdSet/data/DataS1_DT_trai...
629813  /home/gil/comp0173/BirdSet/data/DataS1_DT_trai...
769107  /home/gil/comp0173/BirdSet/data/DataS1_DT_trai...

### Load dataset

In [11]:
# test loading dataset
dataset_DT_train = load_dataset("parquet", data_files="/home/gil/comp0173/BirdSet/data/DataS1_DT_train/metadata-train.parquet")["train"]

## Test_5s

### Dataset Format Exploration

In [12]:
# see format for HSN
dataset_exploration = load_dataset("DBD-research-group/BirdSet", "HSN")#, streaming=True)
dataset_exploration

DatasetDict({
    train: Dataset({
        features: ['audio', 'filepath', 'start_time', 'end_time', 'low_freq', 'high_freq', 'ebird_code', 'ebird_code_multilabel', 'ebird_code_secondary', 'call_type', 'sex', 'lat', 'long', 'length', 'microphone', 'license', 'source', 'local_time', 'detected_events', 'event_cluster', 'peaks', 'quality', 'recordist', 'genus', 'species_group', 'order', 'genus_multilabel', 'species_group_multilabel', 'order_multilabel'],
        num_rows: 5195
    })
    test: Dataset({
        features: ['audio', 'filepath', 'start_time', 'end_time', 'low_freq', 'high_freq', 'ebird_code', 'ebird_code_multilabel', 'ebird_code_secondary', 'call_type', 'sex', 'lat', 'long', 'length', 'microphone', 'license', 'source', 'local_time', 'detected_events', 'event_cluster', 'peaks', 'quality', 'recordist', 'genus', 'species_group', 'order', 'genus_multilabel', 'species_group_multilabel', 'order_multilabel'],
        num_rows: 10296
    })
    test_5s: Dataset({
        features: ['audio', 'filepath', 'start_time', 'end_time', 'low_freq', 'high_freq', 'ebird_code', 'ebird_code_multilabel', 'ebird_code_secondary', 'call_type', 'sex', 'lat', 'long', 'length', 'microphone', 'license', 'source', 'local_time', 'detected_events', 'event_cluster', 'peaks', 'quality', 'recordist', 'genus', 'species_group', 'order', 'genus_multilabel', 'species_group_multilabel', 'order_multilabel'],
        num_rows: 12000
    })
})

In [17]:
dataset_exploration["test_5s"].features

{'audio': Audio(sampling_rate=32000, mono=True, decode=False, id=None),
 'filepath': Value(dtype='string', id=None),
 'start_time': Value(dtype='float64', id=None),
 'end_time': Value(dtype='float64', id=None),
 'low_freq': Value(dtype='int64', id=None),
 'high_freq': Value(dtype='int64', id=None),
 'ebird_code': ClassLabel(names=['gcrfin', 'whcspa', 'amepip', 'sposan', 'rocwre', 'brebla', 'daejun', 'foxspa', 'clanut', 'moublu', 'casfin', 'mallar3', 'herthr', 'amerob', 'yerwar', 'yelwar', 'dusfly', 'mouchi', 'orcwar', 'warvir', 'norfli'], id=None),
 'ebird_code_multilabel': Sequence(feature=ClassLabel(names=['gcrfin', 'whcspa', 'amepip', 'sposan', 'rocwre', 'brebla', 'daejun', 'foxspa', 'clanut', 'moublu', 'casfin', 'mallar3', 'herthr', 'amerob', 'yerwar', 'yelwar', 'dusfly', 'mouchi', 'orcwar', 'warvir', 'norfli'], id=None), length=-1, id=None),
 'ebird_code_secondary': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None),
 'call_type': Value(dtype='string', id=None),
 'sex': Value(dtype='string', id=None),
 'lat': Value(dtype='float64', id=None),
 'long': Value(dtype='float64', id=None),
 'length': Value(dtype='int64', id=None),
 'microphone': Value(dtype='string', id=None),
 'license': Value(dtype='string', id=None),
 'source': Value(dtype='string', id=None),
 'local_time': Value(dtype='string', id=None),
 'detected_events': Sequence(feature=Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None), length=-1, id=None),
 'event_cluster': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None),
 'peaks': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None),
 'quality': Value(dtype='string', id=None),
 'recordist': Value(dtype='string', id=None),
 'genus': ClassLabel(names=['actitis', 'anas', 'anthus', 'catharus', 'colaptes', 'empidonax', 'euphagus', 'haemorhous', 'junco', 'leiothlypis', 'leucosticte', 'nucifraga', 'passerella', 'poecile', 'salpinctes', 'setophaga', 'sialia', 'turdus', 'vireo', 'zonotrichia'], id=None),
 'species_group': ClassLabel(names=['blackbirds', 'finches, euphonias, and allies', 'jays, magpies, crows, and ravens', 'new world sparrows', 'shorebirds', 'thrushes', 'tits, chickadees, and titmice', 'tyrant flycatchers: pewees, kingbirds, and allies', 'vireos', 'wagtails and pipits', 'waterfowl', 'wood-warblers', 'woodpeckers', 'wrens'], id=None),
 'order': ClassLabel(names=['anseriformes', 'charadriiformes', 'passeriformes', 'piciformes'], id=None),
 'genus_multilabel': Sequence(feature=ClassLabel(names=['actitis', 'anas', 'anthus', 'catharus', 'colaptes', 'empidonax', 'euphagus', 'haemorhous', 'junco', 'leiothlypis', 'leucosticte', 'nucifraga', 'passerella', 'poecile', 'salpinctes', 'setophaga', 'sialia', 'turdus', 'vireo', 'zonotrichia'], id=None), length=-1, id=None),
 'species_group_multilabel': Sequence(feature=ClassLabel(names=['blackbirds', 'finches, euphonias, and allies', 'jays, magpies, crows, and ravens', 'new world sparrows', 'shorebirds', 'thrushes', 'tits, chickadees, and titmice', 'tyrant flycatchers: pewees, kingbirds, and allies', 'vireos', 'wagtails and pipits', 'waterfowl', 'wood-warblers', 'woodpeckers', 'wrens'], id=None), length=-1, id=None),
 'order_multilabel': Sequence(feature=ClassLabel(names=['anseriformes', 'charadriiformes', 'passeriformes', 'piciformes'], id=None), length=-1, id=None)}

In [ ]:
samples

{'audio': {'bytes': b'OggS\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\xccG\xbc&\x00\x00\x00\x00\x04X\xb2Y\x01\x1e\x01vorbis\x00\x00\x00\x00\x01\x00}\x00\x00\x00\x00\x00\x00\xb00\x01\x00\x00\x00\x00\x00\xb8\x01OggS\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xccG\xbc&\x01\x00\x00\x00\xca\x9d\x92\xba\x0fZ\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\x91\x03vorbis4\x00\x00\x00Xiph.Org libVorbis I 20200704 (Reducing Environment)\x01\x00\x00\x00\x12\x00\x00\x00ENCODER=libsndfile\x01\x05vorbis&BCV\x01\x00\x08\x00\x00\x80"L\x18\xc4\x80\xd0\x90U\x00\x00\x10\x00\x00\xa0\xac7\x96{\xc8\xbd\xf7\xde{\x81\xa8G\x14{\x88\xbd\xf7\xde{\xe3\xacG\xd0z\x88\xb9\xf7\xde{\xee\xbd\xa7\x1a{\xcb\xbd\xf7\xdes 4d\x15\x00\x00\x04\x00\x80)\x08\x9ar\xe0B\xea\xbd\xf7\x1e\x19\xe6\x11Q\x1a*\xc7\xbd\xf7\x1e\x19\x85\x890\x94\x19\x85=\x95\xdaZ\xeb!\x93\xdcB\xea=\xe7\x1e\x08\rY\x05\x00\x00\x02\x00@\x08!\x84\x14RH!\x85\x14RH!\x85\x14RH)\xa5\x98b\x8a)\xa6\x98b\xca)\xa7\x1cs\xcc1\xc7 \x83\x0e:\xe8\xa4\x93PB\t)\xa4PJ*\xa9\xa4\x94RJ-\xd6Zs\xee\xbd\x07\xdds\xefA\xf8 \x84\x10B\x08!\x84\x10B\x08!\x84\x10B\x08BCV\x01\x00 \x00\x00\x04B\x08!d\x10B\x08!\x84\x14RH!\xa6\x98b\xca)\xa7\x80\xd0\x90U\x00\x00 \x00\x80\x00\x00\x00\x00I\x91\x14\xcb\xb1\x1c\xcd\xd1\x1c\xcd\xf1\x1c\xcf\x11%Q\x12%\xd12-\xd3R5S3=UTE\xd5TUWU]]wm\xd5vm\xd5\x96m\xd7Vm\xd5vm\xd5VmY\xb6m\xdb\xb6m\xdb\xb6m\xdb\xb6m\xdb\xb6m\xdb\xb6m 4d\x15\x00 \x01\x00\xa0#9\x92#)\x92")\x92\xe38\x92\x04\x84\x86\xac\x02\x00d\x00\x00\x04\x00\xa0(\x8a\xe38\x8e\xe4H\x8e%i\x92fy\x96g\x89\x9a\xa8\x99\x9a\xe8\xa9\x9e\n\x84\x86\xac\x02\x00\x00\x01\x00\x04\x00\x00\x00\x00\x00\xe0x\x8a\xe7x\x8egy\x92\xe7x\x8egy\x9a\xa7i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i\x9a\xa6i@h\xc8*\x00@\x02\x00@\xc7q\x1c\xc7q\x1c\xc7q\x1cGr$\x07\x08\rY\x05\x00\xc8\x00\x00\x08\x00@R$\xc7r,Gs4\xc7s<GtD\xc7tL\xc9\x94T\xc9\xb5\\\x0b\x08\rY\x05\x00\x00\x02\x00\x08\x00\x00\x00\x00\x00@\x13,ES<\xc7\x93<\xcf\x135\xcf\xd34\xcd\x13MQ4M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34M\xd34MS\x14\x81\xd0\x90U\x00\x00\x04\x00\x00!\x9df\x96j\x80\x083\x90a 4d\x15\x00\x80\x00\x00\x00\x18\xa1\x08C\x0c\x08\rY\x05\x00\x00\x04\x00\x00\x88\xa1\xe4 \x9a\xd0\x9a\xf3\xcd9\x0e\x9a\xe5\xa0\xa9\x14\x9b\xd3\xc1\x89T\x9b\'\xb9\xa9\x98\x9bs\xce9\xe7\x9cl\xce\x19\xe3\x9cs\xce)\xca\x99\xc5\xa0\x99\xd0\x9as\xceI\x0c\x9a\xa5\xa0\x99\xd0\x9as\xcey\x12\x9b\x07\xad\xa9\xd2\x9as\xce\x19\xe7\x9c\x0e\xc6\x19a\x9cs\xcei\xd2\x9a\x07\xa9\xd9X\x9bs\xceY\xd0\x9a\xe6\xa8\xb9\x14\x9bs\xce\x89\x94\x9b\'\xb5\xb9T\x9bs\xce9\xe7\x9cs\xce9\xe7\x9cs\xce\xa9^\x9c\xce\xc19\xe1\x9cs\xce\x89\xda\x9bk\xb9\t]\x9cs\xce\xf9d\x9c\xee\xcd\t\xe1\x9cs\xce9\xe7\x9cs\xce9\xe7\x9cs\xce\tBCV\x01\x00@\x00\x00\x04a\xd8\x18\xc6\x9d\x82 }\x8e\x06b\x14!\xa6!\x93\x1et\x8f\x0e\x93\xa01\xc8)\xa4\x1e\x8d\x8eFJ\xa9\x83PR\x19\'\xa5t\x82\xd0\x90U\x00\x00 \x00\x00\x84\x10RH!\x85\x14RH!\x85\x14RH!\x86\x18b\x88!\xa7\x9cr\n*\xa8\xa4\x92\x8a*\xca(\xb3\xcc2\xcb,\xb3\xcc2\xcb\xac\xc3\xce:\xeb\xb0\xc3\x10C\x0c1\xb4\xd2J,5\xd5Vc\x8d\xb5\xe6\x9es\xae9Hk\xa5\xb5\xd6Z+\xa5\x94RJ)\xa5 4d\x15\x00\x00\x02\x00@ d\x90A\x06\x19\x85\x14RH!\x86\x98r\xca)\xa7\xa0\x82\n\x08\rY\x05\x00\x00\x02\x00\x08\x00\x00\x00\xf0$\xcf\x11\x1d\xd1\x11\x1d\xd1\x11\x1d\xd1\x11\x1d\xd1\x11\x1d\xcf\xf1\x1cQ\x12%Q\x12%\xd12-S3=UTUWvmY\x97u\xdb\xb7\x85]\xd8u\xdf\xd7}\xdf\xd7\x8d_\x17\x86eY\x96eY\x96eY\x96eY\x96eY\x96e\tBCV\x01\x00 \x00\x00\x00B\x08!\x84\x14RH!\x85\x94b\x8c1\xc7\x9c\x83NB\t\x81\xd0\x90U\x00\x00 \x00\x80\x00\x00\x00\x00Gq\x14\xc7\x91\x1c\xc9\x91$K\xb2$M\xd2,\xcd\xf24O\xf34\xd1\x13EQ4MS\x15]\xd1\x15u\xd3\x16eS6]\xd35e\xd3Ue\xd5ve\xd9\xb6e[\xb7}Y\xb6}\xdf\xf7}\xdf\xf7}\xdf\xf7}\xdf\xf7}\xdf\xd7u 4d\x15\x00 \x01\x00\xa0#9\x92")\x92"9\x8e\xe3H\x92\x04\x84\x86\xac\x02\x00d\x00\x00\x04\x00\xa0(\x8e\xe28\x8e#I\x92$Y\x92&y\x96g\x89\x9a\xa9\x99\x9e\xe9\xa9\xa2\n\x84\x86\xac\x02\x00\x00\x01\x00\x04\x00\x00\x00\x00\x00\xa0h\x8a\xa7\x98\x8a\xa7\x88\x8a\xe7\x88\x8e(\x89\x96i\x89\x9a\xaa\xb9\xa2l\xca\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba\xae\xeb\xba@h\xc8*\x00@\x02\x00@Gr$Gr$ER$Er$\x07\x08\rY\x05\x00\xc8\x00\x00\x08\x00\xc01\x1cCR$\xc7\xb2,M\xf34O\xf34\xd1\x13=\xd13=UtE\x17\x08\rY\x05\x00\x00\x02\x00\x08\x00\x00\x00\x00\x00\xc0\x90\x0cK\xb1\x1c\xcd\xd1$QR-\xd5R5\xd5R-UT=UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU\xd54M\xd34\x81\xd0\x90\x95\x00\x00\x10\x00\x00\r:\xf8\x1a{\xc9\x98\xc4\x92{h\x8cB\x0cz\xeb\x98s\x8ez\xcd\x8c"\xc8q\xec\x103\x88y\x0b\x95#\x04y\x8d\x99D\x88q 4dE\x00\x10\x05\x00\x00\x18\x83\x1cC\xcc!\xe7\x9c\xa4NR\xe4\x9c\xa3\xd2Qj\x9cs\x94:J\x1d\xa5\x14k\xca\xb5\xa3TbK\xb56\xce9J\x1d\xa5\x8cR\xca\xb5\xb4\xdaQJ\xb5\xa6\x1a\x0b\x00\x00\x08p\x00\x00\x08\xb0\x10\n\rY\x11\x00D\x01\x00\x10\x08!\xa5\x90RH)\xe6\x9cr\x0e)\xa5\x9cc\xce!\xa6\x94s\xca9\xe5\x9c\x83\xd2I\xa9\x9cs\xd29)\x91R\xca9\xe5\x9cr\xceI\xe9\x9cT\xce9)\x9d\x84\x02\x00\x00\x02\x1c\x00\x00\x02,\x84BCV\x04\x00q\x02\x00\x0e\xc7\xf1<I\xd3DQ\xd24Q\xf4L\xd1u=\xd1t]I\xd3LS\x13EU\xd5DQUMW\xb5m\xd1Te[\xd24\xd3\xd4DQU5QTUQ5m\xd9TU\xdb\xf6L\xd3\x96M\xd7\xd5mQUu[\xb6maxm\xdb\xf7=\xd3\xb4mQUm\xddt][wm\xd9\xf7e[\xd7\x8dG\xd3LS\x13EW\xd5DQuMW\xd5mSum]\x13E\xd7\x15UW\x96E\xd5\x95eW\x96u_\x95e\xdd\xd7D\xd1uE\xd5\x94]Que[\x95]\xdfveY\xf7M\xd7\xf5uU\x96\x85_\x95e\xe1\xb7u]\x18n\xdf7\x9eQUu_\x95]\xdfWe\xd9\x17n\xdd6~\xdb\xf7\x85g\xd24\xd3\xd4D\xd1U5\xd1T]\xd3Uu\xddt]\xdb\xd6D\xd1uEW\xb5e\xd1T]\xd9\x95m\xdfW]\xd9\xf65Qt]\xd1UeYtUYVe\xd9\xf7]Y\xf6uQU}[\x95e\xdfW]\xd9\xf7m\xdf\x17\x86\xd9\xd6}\xe1t]]We\xd9\x17VY\xf6}\xdb\xd7\x95\xe5\xd6u\xe1\xf8L\xd3\xb6M\xd7\xd5u\xd3u}\xdf\xf6ug\x99u]\xf8E\xd7\xf5}U\x96}c\xb5e_\xf8\x85\xdf\xa9\xfb\xc6\xf1\x8c\xaa\xaa\xeb\xaa\xed\n\xbf*\xcb\xc2\xb0\x0b\xbb\xf3\xdc\xbe/\x94u\xdb\xf8m\xddg\xdc\xbe\x8f\xf1\xe3\xfc\xc6\x91k\xdb\xc21\xeb\xb6s\xdc\xbe\xae,\xbf\xf33~eXz\xa6i\xdb\xa6\xeb\xfa\xba\xe9\xba\xbe/\xeb\xba1\xdc\xbe\xaf\x14U\xd5\xd7U[6\x86\xd5\x95\x85\xe3\x16~\xe3\xd8}\xe18F\xd7\xf5}U\x96}c\xb5ea\xd8}\xdfx~ax\x9e\xd7\xb6\x8d\xe1\xf6}\xcal\xebF\x1f|\x9f\xf2\xcc\xba\x8d\xed\xfb\xc6r\xfb:\xe7w\x8e\xce\xf0\x0c\t\x00\x00\x18p\x00\x00\x080\xa1\x0c\x14\x1a\xb2"\x00\x88\x13\x00`\x10r\x0e1\x05!R\x0cB\x08!\xa5\x0eBJ\x11c\x102\xe7\xa4d\xccI\t\xa5\xa4\x16JI-b\x0cB\xe6\x98\x94\xcc9)\xa1\x94\x96B)-\x85\x12Z\x0b\xa5\xc4\x16Ji\xad\xb5Vkj-\xd6\x10Jk\xa1\x94\x18C)-\xa6\xd6jL\xad\xd5\x1a1\x06!sNJ\xe6\x9c\x94RJk\xa1\x94\xd62\xe7\xa8t\x0eR\xea \xa4\x94Rj\xb1\xa4\x14c\xe5\x9c\x94\x0c:*\x1d\x84\x94J*1\x95\x94b\x0c\xa9\xc4VR\x8a\xb5\xa4Tck\xb1\xe5\x16c\xce\xa1\x94\x16K*\xb1\x95\x94bm1\xe5\x18c\xcc9b\x0cB\xe6\x9c\x94\xcc9)\xa1\x94\xd6JI-V\xceI\xe9 \xa4\x949(\xa9\xa4\x14c))\xc5\xcc9I\x1d\x84\x94:\xe8(\x95\x94bL-\xc5\x16J\x89\xad\xa4Tc)\xa9\xc5\x16c\xce-\xc5XCI-\x96\x94b-)\xc5\xd8b\xcc\xb9\xc5\x96[\x07\xa1\xb5\x90J\x8c\xa1\x94\x18[\x8c9\xb7\xd6j\r\xa5\xc4XR\x8a\xb5\xa4Tc\x8c\xb5\xf6\x18c\xce\xa1\x94\x18K*5\x96\x94bm5\xf6\xdab\xac9\xb5\x96kj\xb1\xe6\x16c\xcf\xb5\xe5\xd6k\xce\xbd\xa7\xd6jM\xb1\xe5\xdab\xcc=\xe6\x18d\xcd\xb9\x07\x0fBk\xa1\x94\x16C)1\xb6\xd6jm1\xe6\x1cJ\x89\xad\xa4Tc))\xd6\x18c\xce-\xd6\xdaC)1\x96\x94b-)\xd5\x1ac\xcc9\xd6\xd8kj-\xd7\x16c\xcf\xa9\xc5\x9ak\xce\xc1\xc7\x98cO-\xd6\x1cc\xcc=\xc5\x96k\xcd\xb9\xf7\x9a[\x90\x05\x00\x00\x0c8\x00\x00\x04\x98P\x06\n\rY\t\x00D\x01\x00\x10\x84(\xc5\x18\x84\x06!\xc6\x9c\x93\xd0 \xc4\x98sR*\xc6\x9c\x83\x90J\xc5\x98s\x10J\xca\x9c\x83PJJ\x99s\x10JI)\x94\x92JJ\xad\x85RJJ\xa9\xb5\x02\x00\x00\n\x1c\x00\x00\x02l\xd0\x94X\x1c\xa0\xd0\x90\x95\x00@*\x00\x80\xc1q,\xcb\xf3DQ5e\xd9\xb1$\xcf\x13E\xd3TU\xdbv,\xcb\xf3D\xd14U\xd5\xb6-\xcf\x13E\xd3TU\xd7\xd5u\xcb\xf3D\xd1TU\xd5uu\xdd\x13E\xd5TU\xd7\x95e\xdf\xf7D\xd14U\xd5ue\xd9\xf7M\xd3tU\xd7\x95e\xdb\xf6}\xd34U\xd7ueY\xb6}auU\xd7\x95e\xdb\xd6mcXU\xd7ue\xd9\xb6m]9n\xdd\xd6u\xe1\x17\x86a\x98\xda\xba\xee\xfb\xbe/\x0c\xc7\xf0L\x03\x00\xc0\x13\x1c\x00\x80\nlX\x1d\xe1\xa4h,\xb0\xd0\x90\x95\x00@\x06\x00\x00a\x0cB\x06!\x85\x0cBH!\x85\x94BH)%\x00\x00`\xc0\x01\x00 \xc0\x842Ph\xc8J\x00 \x15\x00\x00 \xc4Zk\xad\xb5\xd6Zb\xa9\xb5\xd6Zk\xad\xb5\x86Jk\xad\xb5\xd6Zk\xad\xb5\xd6Zk\xad\xb5\xd6Zk\xad\xb5\xd6Zk\xad\xb5\xd6Zk\xad\xb5\xd6Zk\xad\xb5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\xa5\x94RJ)\x15\x00\xe8W\xe1\x00\xe0\xff`\xc3\xea\x08\'Ec\x81\x85\x86\xac\x04\x00\xc2\x01\x00\x00c\x94b\x0c:\xe9$\xa4\xd40\xe5\x18\x84RRI\xa5\x95F1\xe7 \x94\x92RJ\xadU\xceIH\xa5\xa5\xd6Z\x8b\xb1rNJI)\xb5\x16[\x8c\x1d\x84\x94Zj-\xc6\x18c\xec \xa4\x94Zk1\xc6\x18c(\xa5\xa5\x18c\xac1\xd6ZCI\xa9\xb5\x18c\x8c5\xd7ZRj-\xc6Zk\xad\xb9\xf7\x92R\x8b1\xc6\\k\xee\xb9\x97\xd6b\xac\xb5\xe6\x9cs\xce=\xb5\x16c\xad5\xe7\xdcs\xf0\xa9\xb5\x18c\xce\xb5\xf7\xde{P\xad\xc5Xk\xae9\x07\xe1{\x01\x00\xdc\r\x0e\x00\x10\t6\xce\xb0\x92tV8\x1a\\h\xc8J\x00 $\x00\x80@\x881\xc6\x9cs\x0eB\x08!DJ1\xe6\x9cs\x10B\x08!\x84H)\xc6\x9cs\x0eB\x08!\x84\x901\xe6\x9cs\x10B\x08\xa1\x94R2\xc6\x9cs\x0eB\x08%\x94PJ\xe6\x9cs\x10B\x08\xa1\x94RJ\xc9\x9cs\x0eB\x08!\x94RJ)\x1dt\x10B\x08\xa1\x94RJ)\xa5s\x0eB\x08\xa1\x94RJ)\xa5\x84\x10B(\xa5\x94RJ)\xa5\x94\x10B\x08\xa5\x94RJ)\xa5\x94\x12B\x08\xa5\x94RJ)\xa5\x94RB\x08\xa1\x94RJ)\xa5\xa4RJ\x08\xa1\x94RJ)\xa5\x94RJ\t!\x94RJ)\xa5\x94RJ)\xa1\x84RJ)\xa5\x94RJ)%\x94PJ)\xa5\x94RJ*\xa5\x14\x00\x00p\xe0\x00\x00\x10`\x04\x9ddTY\x84\x8d&\\x\x00\n\rY\t\x00\x00\x01\x00 \xceZl)FF1\xe7 \x86\xc8 \xc4 \x86\n)\xc5\x9c\xb5\x0c)\x83\x1c\xa6L)\x84\x94\x95\xce1\x86\x88\x93\x16[\x0b\x15\x03\x00\x00@\x10\x00@ d\x02\x81\x02(0\x90\x01\x00\x07\x08\tR\x00@a\x81\xa1C\x84\x08\x10\xa3\xc0\xc0\xb8\xb8\xb4\x01\x00\x08Bd\x86HD,\x06\x89\t\xd5@Q1\x1d\x00,.0\xe4\x03@\x86\xc6F\xda\xc5\x05t\x19\xe0\x82.\xee:\x10B\x10\x82\x10\xc4\xe2\x00\nH\xc0\xc1\t7<\xf1\x86\'\xdc\xe0\x04\x9d\xa2R\x07\x01\x00\x00\x00\x00\x80\x00\x00\x0f\x00\x00\xc7\x06\x10\x11\xd1\x1cG\x87\xc7\x07H\x88\xc8\x08II\x00\x00\x00\x00\x00\x00\x01\xc0\x07\x00\xc0a\x02DD4\xc7\xd1\xe1\xf1\x01\x12"2BR\x12\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x04\x04\x00\x00\x00\x00\x00\x02\x00\x00\x00\x04\x04OggS\x00\x00@F\x00\x00\x00\x00\x00\x00\xccG\xbc&\x02\x00\x00\x00{!\xa2\x9b\x13,\xec\xe2\xda\xed\xe6\xe1\xed\xe7\xeb\xe6\xec\xea\xe3\xdd\xe5\xe1\xe2\xe0T\x89\x88\x10\x9b1\xb5\xd0\x00\x18\x1c\xab\x80K\x87\x1c\xa6\x1cL\x105\x8c\x7fg\xe6\xbc\xef\xde\xa0\x8c\xdf9\x04\xf3w\xf3\xb0G\xe8\x15\x8c\xb3V\x02z\xa6\x81\xa3\xe1\xa5m\x01\x80w\xbf\xfekw\xbe-\\\xf5\xf4\xf24\x8f\x8a\x89\xab\xfb\xe64\x9f\xc7\xb2,\x90\x01\x802A\xac\xa8\xaal\xa3D8O9\xc3^\xb2\xb7q\xcd>\xbaS\xc9\xd3\xbdki\xff\xd1\x9c\xcc\x87\xa9B8\xdd\xb8`\xe6}\x87\x9e\x95r\xd2v\xe6\xe3wE\xda\x874\xc74_\xeb\xc0\xf0\x1d\x99\xb2fN\x9d\xdaL?\xc6\xf0\x1d\xd8\x95fE\xd2f\xa3d\xe3=`[Nj\xa22\xbf*\td%\xeb\xff;\xbc\xb7d\xbc\x99d\xd1\xc9\x1d\xa5\xc4\xe58\x9dt\x9c~\xb4\xf6J\xa9r\x1f5y\xc1y\x97\x17&4SG\xe2*F\xbf\xd1D\xa6\xcdu\xce\x99\x90\xc7~uw\x97\xf5/v\xd0\x90\xa5\xdb ~\x15\x8dl\x0cr\xfe\xf3\xc9,\xcal\xebh\xc7Q\xe3c\xde\xb1@\xa0\xc3,\xd2\xbfm\xcc\xcb\xb9.LkO@\xfe\xf2\xee-\x1ds\xba\xa6\xa9B&wR\xae\x01\xfe\x96qM\x00\\\x00\x00\x7f\xc9\x06\xe2X%\x8f>d=#\xd1\xbd\xbc\r\x92hT9)\x89\xb8\xb605\xbd\xe8\xd7\xbd=\xa5n\xd2\xd7\x7f\xa6ik\x82\xadC?\xdc\xear\t\xba\x9e\xb5l\x01\xcc\xaf\x9e\xf6]\x7fz\x91u\rG\xbd\xcd\xef\xf9j\x9f\xa8Nr\xb9m\xc0\xe4v1\xdc\xe1\xbf\xb1\x12\xe1\xf8\x04N\xb5\x7f\xa4\xe8\x10\xb55Z\xd1N|!\xd0\x91\xd9\x9aXOZ\x13L/\x9fU\x81PMp\t\x84w\x07)\x1d\xe6\xb9\xc8d\xf9!3\xe8YU\x9df\xa8:\x96\xaa\x1cU\xf2\xbd\x82"?\x03\xbb\xed\xe00\xcb\xe1\x1c\xa3:\x93\x9f\xc1]\rT\x02\xd2\xdf\x92\x92\xcbR\x89\xf01\xec\xfdT\xf7\x0e\x1ei\xf5V\xe2\xa0\x94c7\x83\x02%X\x8f\xdd\xa7=\xc5\xc6\xf9\x03\xad^!\xec\xbb\xcb\xab^\xaa<\x902\x9c\x1c\x99\xbb\x9cS\x89ykZ\x00\x1e\xb7q]\x02l\x01\x80\x9f\xd4hI\xd7\xc7\x08=\xfa\xc0\xf6\x02=\xda*\xebU\x95U%B\x17\xb3?{\xc3\r~\xb4>\xde\xa7qe\xee\xb6%\xe7s\x9f1\xa3q\xfa\x9c\xd4\xbcza\xc2B\x98\xa8\xf6\x01\x86\xf6\x96\xa4\xca.n\x85\x82\xdd\xf8\xeac\xf6\xb0\xe7\x06oP\xc5\xbf\xf2l5\xd1\x85om\x94\x16\xa5$\xeaI\xc2\xf4`\xa1\x13\x89\x11\x1e\xfb,\x88Z\xd4R\x81:\xa5\x9aa|\xea\xe7\xe4\xb5\xc2\xf5\xb7U\xc4\xc2\x99\x1d7\xe7\x91\xc4V\xa6\x8bRn\xe7\xbb\xf6\xb0\xf0pIR\xbfTV\x94\rF\xe1>S5\xbb\x88Izu\x81\xcd\xd8\x01\xdaW=)\\\x8d\x9b2\xd46\xbdj2\x95\x15\xf6`Z\xc2\xcc~\xf3\x82\x11Y,\x92y\x82\x02QY\x14#\xb3\xa3\xf4\xf0\xf6E\xa3Yy\xb3\xa3$A\xbc\x0ep\xbc\x16\x00\xbe\x96\xa1^#[m<\x01\xe0g\n\x91j\x99F\xee\xee\x89\xd6\x84nz\x98\x11\x83\x05\xa0b,\r\xd4[\xb5Q\xe2\xb0\x9a\xbf\xd6\xdbN\xea\x93b\xe7{\xfe_\xfb\xfa\xe2f|\xf2\xf5t\x0f3\xe5\xa0y\x10\xea\x8cy\xa9\xfe\xed\xb9\xce\xea\x92P\xc1\t\xa9}\xb2\x11\x9a5\x93\x14\xafV\x13\xc9s*\xebgbZ\xb0\xbc\n\x8e5\x9bG#bi\xa9\xb6\\\xab\x97\x9c3B\x94P~\xab\xa2\xb0n\xc3\\n<^\xaaRDJk_\xcb\x8b\xc7O=\xe8\x87~\xfc\xa8\x9c\xb3\xa7\xca\xc9\x05\xb8\x0f\xd0\x86b\x01\xd6\x85)\xcc\xf3c\xb1~\xa2\xbc\x9f`\xb3\xf7\xc8;zg\xa4\x84\xde&\x97\x02s\xb1\xdd\x16\x10\xbbM\xf5ha<\x18\x1e\xd8\x05\xb6{\xa3\x91\xac\xdbw\x96\xf23+\x15\x0f5\xedY\xf5J.\xbe\xfb\xdb\x11G\xfe\nQM\xde2/\x15\xfe\xca\x9b\xe7\xd6\x1f\xdf\xebf%w\xcc\x99\x02~\xa6\xa1E\x001\x02\x00\xdf\xeey\x1dd\xca\xba\xb0\xc4X\xd7<\xdaA\xf4\xaa$I\x8cQU[\x12\xe2\xe7\xde!\t\xefkg\xa5_0!\xc9\xcf\xd3\x93a[\x82\xe4\xe0\xe4\xf0\xe5=\xe9\xc7\t}X\xb8a\xac%6NPs:\x8d\x1el\x95}{\xcc$kM\xb6M3\xc3\x03\xdb\xc3Ka\x93\xd3\xa7\x7f\xe5\x96\xdd\xb0W\xa2\x19F\x84\x16E\x08\xf9\xce\xe1[f\xb2).k\xed\x17\xe0\x17\xbb\x1a\xb6\x0e\x92\xe4\xd0\xca\xa2\x8a\x96\xd4\xbb\xd2\x0f\xd7\x1f,\xe7F#\xa2\x8a]\xday\x81\xd2\xbf\x12v\xc0\x89\x17\x19\xee\x8bsD\x8c\x8cR\xd9\x94}\x0c;\x1b\xcc\xc6\x13\'\x9e\xf1x\xdf\x01\xad1?rK\xe7W\xb1\xb0\xd5S|0\x17(\xa0\xc6\x13e.W\xd5\xbb\xa6\xea r\xb1^\xe0\x8e\x0b\xd4\xcaE>\xe6\xc9\xc1\x9a\xf98\xed\x99t\xe5\xec1\'\xfc\x1eEK\x81\x04\xbe\xc6aE\x025\x00\x00\x7f\xc5\xa29\\[8\xb4\x14\x8dE\x8e*kcyU\x8d\x8e\x04\xe9\xb7w\x9f\xd5\x06z\xba\xac\xe6\x0e\xf5\xa0\xe7]\x93\xa3<\x95}=\x8c\xce\xba\xa7\xc4y\x99\x83\x94-\xfbX3\xcf\x1b\xc5C\x9f"\x84\xf3\xc8mS\xac\x86\xaf2;\xe9\xcf\n\xfb<^I\xa2<\x00\x1cX\xf7\xc7r \x17\x11$\xc6\xee\xd0\x86\xa5?\x83\xca8\x91t\xbf_\xfe\xb2])O\xa5\x18\xd45\xd3\xcd\x0b\xb3\xe90H\xf4\xc3!w}u\xbe\x9f\x0b,\x9e\xb8\x07C$~XI&w\xcb\x9c\xd7\x95\\?\xb6\xb8y.\xd1\x90\xb9\xf2\xbd`\x07P\xd0\xd7[\xaa\x01#S\x90I\xa2\x95\xabm\xc4\x14\xc8f\xe8C>\xce\x85/1\xb7\x1f5M\xacP\x85|\xb0B\xc6\x98\xf1Hh\x96\xe2\x14\x8d\xb8\n\xc3U\x96^\xfe3$\xac[i\x12\x18\xad\rw\x00\x9e\x97\x89\x93@\x12\x1b7\x00\xfct\xd1=oF\x8a\xa8\xd5\xb2\xed\x1e\xc1\xb29WRYUUm\x94x\xb3\xf4\xddaw\xa8\x95\x1b\xd7\xf4\xdc\xff?5\x84\xa5\x855\xbd\xfb\x86+\xa2\xb7\xf5\x05k\x05\xad\x9c\x1aR\xbe\xf2+\xa7^\xc4U>\xcd\xd3\x02\x17\x1ee.~\xcd\x0c\xc5\xc5+\xeb\x0c\x1bv\x9f\x8a\xd7D%\xefJ\xd3\x9e%2(1\xbckj\xc7\xca\x18%\x17\xee\xbdeb\x00%\xb3o\xfb\xe8Q\x1c\xcd\xe5\xd9-#\xccO\xdf\x89;^Z*\x8cu,\xc18\xed/3\xe6\x8f&\xc8\x95\xde\xe5\x15\xd8\x1ba\x16\xee\x84\x12\x16\xedzT\xbbl\xf5t\xa5\xb4\xd5\x085\xfdHk_\x87K\x97-H6\xa1\x93\xa6\xa7\xca\xaa\xd8N"-\xddJM\xf4K\x90j6\xde\x93\x9e1e\xcf\xb9Z|\xbc\xa6\xc8\x07\xe6M\xfc\xba\xc8^\x05M\xf1\xc7\xffhU\xce4\xaa)\x94\xb2ks\x8e=\xe7\x02^\x97\xf1\xa3&\xd0\xad\x03\x00\x9f\xde4m\xcc\x1d\xc5\xcbv\x04=\xcc\x81#\xf4\xb2ZeT\x95\xb4V"o\x91_\xeb\xd7\x91\x9f\x1e!\x1b2r~\xbaS*\x1a\x9b\xc4U\xef\xaes\xf4\xf8u^\x9e~\xa5u\xf1|[,\xd8hl\x06\x80\x94\xdb\x02\xbe\xf7\xb8\r\x82\xd5\x8fji\xad\x917C@f8U,\xea\x92\x9d\x19\'\xcdNK\x0b\x88\x82\n\xcb59\x124\xecq\xe3\xb9%\x15\xeb\x07M\x80#*\\\xf5b\xac\x16\x89T-\x88\x88\xa8}*Y\x8f\x86\x94F\x96\xee\x9e\x04m\xf9r.\x1f\x15\xd2a\xcb3\xea]\xb7M\x1f\x8e\x11\xdfy\xe2RNe\xa2\xd4VwR\xf8\xb7Xo\xcf\xfb}\x89\xcc\xb3/C`\x99\x86y\xa4\xdcm\xba\xaa\x18\xda\xdf\x8d\x13\x9f\xa5\xecZ\xb3\xf9\x84\xfb\x8a\xaf\xb5\x10=\xb2D\x9f\xa2\xd5#\xeay\xad\xac\x10]\xc6\x16\xeb\xde\x03\xdbu\x00\x9e\x971\xa3\xc1\x9b_\xb8\xd1\x00\xde\x13\x90\xed\xa0\xcf\xe5q\xe4\xdcH26b\xe6\x80\x06\xa0\'\x81\xadDU5)\x89+\xda\xbd\x96\xcfzz\x8c\xb3Kk1\x9d\x84\xc6\xbc!\xef?]Q1\x98$\xdc\x97\x08m\x93\xc2\xd4\x08\x95\x97|!u\x98P\x95\x95\xb45\x1c\x1e\xd82>Y*\xb5_\x88\xc3\xcaP\xe6\xb7\x8f\xd3\xbd\'D\x0e\xb1%\xdb:<\xf7Bf+Rq{\xceW&B\x15\xc7\xc9\xb67vD\xb8\xd7Dk6\xfd\xe1B5\xd9&Z\xea9s4\x96\x95\x89\xc0\xc5,@jf\xe1n\x9b0JE`\xc7\xcf\xa0gBI\tr\xbf^\xd9m\xe7\\\x90t\x0b~\xbaa\xf1}\x93=\x01\x02\x8d\xa0t\\\x874^O\xd0Vi\x17\xa9@*\xa4Dm\xc6\x07Bz\x12\xce\x92*]\xfc\x0bg:\xbc\x9f\xc0\xd1\xec\x99Qz\xf6\xab\xc3\x18\xa2\x1c\xdb\xdaW~\xd9\x95\xca\x02\x00\x1e\xb8\xa9\xa3\x06bt\x00\xe0\x93\'\xb0+zwWd`u\r\xf4\xaaX\x15\xf6Q\xd5\xaa\xc4\xa9A\xc5}\x8a\xd6ns\xb7\x83\xb5\xe6\xb7\xa6\xdf\xf9\xa5Z\xb5\xcf\x8d\xf0\x8d\xd6\xdb}P\x9b\x96\xe1\x96\xcf6SC\xb02\x8e7\xec\xed\xa7B\xcc1\xb8H\xbc@_i\x11\xff\xcb9\xfd\x1b2\xce\xa8Sc\x0e\xa6\x9bE\x9b\xe9\xb5\xbb\xc6\x91!=\x9c;U\xadc\xcb\xd4\xf6\x9er\x0f\x06\x1f\xda\xda7\x11\xd8\xcb\x812;\x89P\x95\xf4-\xaf&\xb0\x15\x86\x1dA\x80\xcb\x1c\xff\x9a\xa4\x8b\xc0\x80f\xbe\\\x85\xd5=Sl-j\x1a\x189\xe1\x9d\\D\xc5\xe4G\xc3\xf5\xc6f\x90\xa2`\xb3\x10(\x84\xfd\x04pg\xa0\xaf\xaa*?}@(\x11|i\'\xc8\x83\xa4p\xa3\xd9\x064t8N\x04:\'\x9f\xc0\xbe->\xf7\x1f\xe5\xff\x81\xd8<N\x8f\xbc\xed\x11}\xd2\x95\n3\x00\xbe\x96\x91U\x02\\\x00\x00+\x00@\x8e\xc8\\u\xdani\x91\r$\xa0\xdc\xc0V\x19U\xa3Q\xa2\x12\x00@TM\x0c+\xa6\xe6\xf9\xf7\x10\x12c\x16\xad)#q\xe3\xbdK\xd3\x05Y?6\t\xefL\xd1i\x9b\x15\x1bO\xedi7\xf4fo\xcf\xec\xc5\x8e\xc2A\xa1\xf3B\xcc\xa2\xb0\xc7\x17\xfd\x94\xecM\x0c\xc9g\xf6\xa7\xe8\x9e\r\xd9\x0c\xe2\xd5\x8c\x99:+\xd3\xca \xaf\x98\xab\x0b&\xa0\xd7Y\xca\xcc\rJ\xf1\x18\xf6\xeb9{4\x15y\x9d\xfc\xdd"^\x7f\xc1\x8a1\xe1\xaa[\xc0hY\xd4\x91\xb6K) \xde\x0co8\x18\x1e\x89\x15\xff{\x8e{J\x19\xb1\xd9\xbf9D\x1av\xae\xa9y\xd7\xa6\xb9\rB\xa7\xb3\x8f\xc2!\xb6\x9a\x92\x8bl\x92q\xae\xbad\x04a\xe2r\xc8/5\x02\x12B%^gz~gK\xc5\xd9]g\xc6\xa9\xa1\xf4\xc0\xb0\xa4\x8d\xdc\x8c4\x83o\xbci\xa7\x12|]\x03^\xa7q\xa3\xc6\x10\x1b7\x00\xfcu`\xa3\x0fr;\xe88r\xa4\xda\x06\xdd\xbd\x92\xf2%\x8a\xaa\xea\xa3\xc4S^Hr_\xbe\x94\xf53\x92T:M\x89\xfc\xbe\x9e\xed\xbcg\xe3\xf9\xeb\xbaog\xb8\xd1c\x0cH|\x8d\x08\xf4\xcet\xbe\xae\x1ch\xd5<\xadB\x1cV\xe3\xbd\x07\xa0c9\xdeO9=\x1b\x14Q2r\r%\xbf\x10\x11\xc2+\xf5\x96\x1d\xbf\x9e\x83\xd6\xf3\xb1\x9a\xe3 \x1ddb\xc6\x8d\xbf\xadf\xba\xec\xa0\x8d\xbc#B\x86\xa5bV\xb98\xcc\xdcJ+b<3\x92n\tFb*+\x9d\xcc\xd3\xfd\xcb\x81\xe2L\xcfX\x1do)\xda\xb1p\xf12\xdfl\xc4H2\xc1\x95\xe0;\xeb\xb6\x96\x17\'|\x93\x02^\x95I\xc9rY=\t\xc1\xa8"\xa3\xd5\xba"\xb8p\xb8H2Y\x0c\xe1b\xdf\xdf\xa4\x8fE\xde\xada\x1a\x91\x8az\x1d}L\xdc\x8aw\xfdsVom=\xa6\x8f\x02\xfe\xa6\xd1Q\xa3\xe1[\x1b\x00>\x062\xecF\xc7j\x11\xb2\x89\x94\xd8\xc5\xc6j\x00\xc4\xb2\xa5\xde\xa8T\x1b%r}wK\x97%\xff\xe7[\x08\xcbo\xc67\x92\x10Ck\xc1|s\xa6\xf5\xae=M\xe8H4As\x0283\x98\xae\\\xfb\xca\xd6\x8c\xb76\x88\x08m\x17*;C\xfe\xd9\xb5r?\xd6\xcf\x1ay\xdfl\xc4\x9c@\xd0A\x90\xc1\xa7\t\xde\x01g\xb9\xe0\x82\xf8\xe9\x85/N\xed\x9c\x18\xfd\x8e)NN\xab\xfb\x0bn7\xf8mQ\xaf"Na\x1d\x87\x82\x82\xe8"q%\xa5n\xe7\x9c\x06\xe2\xa3\x9eO\x81W\xd9\xce\xa8CZU\xfcJy\xd8>E7N\xd5\xd6\xa0\x96\xcdr|\x17\x90\xab>\x1d\xf8\xb5\xe7\rU\x00\x11\xaa~(\x88d\xcc-_!\xe7\xc7}X\xc9L\x1f\xaa\x08U\xad\x10\x9a\x12\xf1\x16\xf4\x83\xf0\xb8~\n\xa53;Y\xd7\xc2f\xb8)\x00~6\xa2\xc5\xa0\x04\x1a$\xc0\xe7\xd4\x08\xd9]\xce#:\xb5\xd8\xd9\x06t\xefI\xd4\xc4DUAU!\xb8\xcf\xfb\x7f\x96\xc6j|\xc7\xc8\xfeB\x9a\xf3>tfk\x1a\xefa\xe3RS0\x9f\x9c\x1b^+t"\x91\xfeojBzR[\x1e\x80\xd8\x9c\xaa\x9e\xc6\x94^\xb6\x0fpP&\x81-\xba3\xb5S\xdc"\xb4\xcf\xe2T\xb00\x83{\xa4\xb53\xbb\x19\xc5\x8fKN\x1b\xb6\x91mc\xcbq\x8b\xea(\xbd/,dn\\\xf6\xea,\xc7\x9e\xd8_y\x8e\x9e\x84VP;G\x94\xf5\xb0\x91QE\xeb\x86\xbf{0D\xdd\xb1\xf1AO\n\x0bj*2\xfd\x1f\xbbh~\x1c\xce6\xfa\xd8\x0b*\x19Q\xea\x99\xd9\xea3t\xa6\xafJ\xa5\xcf\x9b_\x10\xc55\xc9\x08\x03k\xd5\x8c@J\xd5\x83:R\xfcZ)\x06=\xa3|\x11\r\xfd^\x92)c\xca\x01\x1e\x97\xa1\xd5\x11\xd5/L\x0c\x80\xd7\xbb\x01\x8c\xedd.{P\xf7\n\x88^\xd1\xcdeTU\xda(\xb1V>\xa4\x8f\xb6,I\xf8eJNR\x85\xd8w8\x96\xc4\xec\xeef{\x12\xdc\xad\xf8\x87\xee`\x15\x1f\xd8^FMS;ES\xce\xd65S\x91\n\x88\x8b?\x0eN#\x7f\x19-\\\xafs\xbb\xd7\xe8\x0bZ\x88X\x90G\xb8{=\x1ey\xc7\x07\xd9>\xd7\x93b G\x9c^;\xcb\xb3\xfa\xa4#\xa2L7#\x0e\xab\xb4nS`\xdb\xd1\xc4{\xcb\xa4\xdb\x91\rk\xe2F\x88\xd5?\x9e\xd8\x88qE\xa0\xfe\xe5\xe5Hv:K\xa7\xd6`\x97\xfeI3&\x80$\xa0\x1a}\\#\xf1\xc9*y"g+]\xf6eB9\x90\xb0:\x93z\xdc\x95\xf6\xea\x05\xaf\x98S_\xee\x83L\xb2\x1d\xbc\xacH\xd1\xe4A\x89p{\xd6yJ\xa6)\x8c\x96\xd5i\xf154\x0eY[\x85\x04~\xb6\xc1\xd1\xe1\xb01\x01\xe0e\n)\xc3\x11\xa3\xeeB\x8c\x8c\x98\x

In [25]:
dataset_exploration["test_5s"]["ebird_code_multilabel"]

[[1],
 [],
 [],
 [4],
 [12],
 [],
 [],
 [2],
 [],
 [],
 [8],
 [1],
 [],
 [],
 [],
 [2],
 [],
 [1],
 [],
 [],
 [6],
 [],
 [],
 [12],
 [2, 1],
 [1],
 [],
 [2],
 [0],
 [],
 [2],
 [],
 [],
 [],
 [],
 [1],
 [2],
 [0, 4],
 [1],
 [8],
 [1],
 [],
 [],
 [],
 [],
 [12, 1],
 [],
 [],
 [],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [4],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [1],
 [1],
 [1],
 [],
 [2],
 [],
 [2],
 [1],
 [],
 [17],
 [1],
 [],
 [4],
 [],
 [1, 2],
 [],
 [4],
 [1, 0],
 [],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [2],
 [1],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [2],
 [],
 [],
 [1],
 [4],
 [1],
 [],
 [1],
 [],
 [1],
 [8],
 [],
 [],
 [],
 [1],
 [],
 [1],
 [],
 [2],
 [6],
 [1],
 [],
 [1, 4],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [1],
 [1],
 [1],
 [],
 [],
 [0],
 [],
 [],
 [],
 [],
 [1],
 [1],
 [4],
 [0, 1],
 [14],
 [2],
 [],
 [1],
 [1],
 [],
 [1],
 [],
 [],
 [],
 [],
 [8],
 [],
 [2],
 [12],
 [],
 [1],
 [],
 [],
 [],
 [2],
 [],
 [],
 [1],
 [1],
 [1, 2],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [1],
 [],
 [2],
 [],
 [],
 [],
 [12],
 [1],
 [],
 [],
 [12, 1],
 [1],
 [0],
 [1, 0],
 [],
 [],
 [],
 [],
 [8],
 [],
 [2],
 [],
 [1],
 [],
 [],
 [1],
 [],
 [],
 [1],
 [0],
 [0],
 [],
 [],
 [6],
 [0],
 [],
 [1, 4],
 [8],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [4],
 [4],
 [],
 [],
 [1, 0],
 [12],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [1],
 [2],
 [4],
 [1, 0],
 [2, 1],
 [1],
 [2],
 [],
 [7],
 [13],
 [1],
 [],
 [2],
 [],
 [2],
 [],
 [1, 4],
 [4, 1],
 [6],
 [1],
 [2],
 [],
 [1],
 [0],
 [],
 [],
 [],
 [],
 [],
 [0],
 [],
 [1],
 [],
 [1],
 [],
 [8],
 [],
 [],
 [],
 [2, 0],
 [],
 [2],
 [],
 [2],
 [],
 [],
 [2],
 [0],
 [],
 [0],
 [],
 [],
 [4],
 [],
 [2],
 [1, 2],
 [],
 [],
 [],
 [],
 [12, 16],
 [],
 [0],
 [],
 [],
 [1],
 [1],
 [],
 [1, 2],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [1, 12],
 [],
 [0],
 [],
 [6],
 [],
 [1],
 [],
 [1],
 [],
 [],
 [],
 [],
 [2],
 [],
 [0],
 [1],
 [4],
 [4],
 [12],
 [],
 [1],
 [],
 [],
 [],
 [2],
 [],
 [13],
 [],
 [],
 [1],
 [],
 [],
 [],
 [1],
 [],
 [],
 [1, 0],
 [],
 [2],
 [],
 [],
 [],
 [],
 [],
 [1],
 [],
 [1],
 [1],
 [],
 [],
 [0],
 [],
 [4],
 [1],
 [],
 [8],
 [8],
 [],
 [1],
 [],
 [],
 [1],
 [],
 [1],
 [],
 [1],
 [],
 [8],
 [4],
 [1, 8],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [2],
 [],
 [0],
 [2],
 [19],
 [2],
 [0, 1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [2],
 [],
 [],
 [1],
 [],
 [4],
 [],
 [],
 [1],
 [4, 1],
 [0],
 [2],
 [],
 [12],
 [],
 [],
 [3],
 [1],
 [],
 [],
 [1],
 [1],
 [1],
 [12],
 [],
 [],
 [1],
 [6],
 [],
 [],
 [],
 [2],
 [2],
 [1, 9],
 [],
 [],
 [1],
 [],
 [1, 4],
 [],
 [1],
 [12],
 [],
 [],
 [],
 [],
 [2],
 [],
 [1, 2],
 [2],
 [],
 [2],
 [],
 [],
 [],
 [],
 [1, 0],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [1, 2],
 [],
 [1],
 [],
 [1, 17],
 [1],
 [],
 [12],
 [1],
 [],
 [2],
 [1],
 [],
 [],
 [1],
 [],
 [8],
 [1],
 [],
 [],
 [],
 [17],
 [],
 [2],
 [1],
 [],
 [],
 [1],
 [],
 [6],
 [],
 [1, 2],
 [],
 [12, 1],
 [14],
 [],
 [1],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [1],
 [0],
 [],
 [],
 [],
 [1],
 [2],
 [1],
 [],
 [1],
 [1],
 [],
 [17],
 [],
 [],
 [],
 [1],
 [],
 [2],
 [],
 [0],
 [],
 [],
 [8],
 [],
 [],
 [8],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [1],
 [],
 [0, 1],
 [],
 [],
 [1],
 [],
 [],
 [],
 [4],
 [0],
 [0],
 [1],
 [],
 [],
 [12, 13],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [9, 6],
 [],
 [0],
 [2],
 [0],
 [],
 [1],
 [2],
 [],
 [],
 [1],
 [1],
 [],
 [12],
 [1, 14],
 [4],
 [8, 4],
 [4],
 [1],
 [1],
 [2],
 [1],
 [8],
 [],
 [],
 [6],
 [1],
 [0, 1],
 [],
 [1, 4],
 [1],
 [0],
 [0],
 [],
 [0],
 [4],
 [4],
 [],
 [],
 [],
 [],
 [],
 [13, 1, 12],
 [2],
 [1],
 [],
 [],
 [],
 [],
 [],
 [1],
 [0],
 [1],
 [],
 [1, 2],
 [],
 [],
 [0],
 [4],
 [],
 [0],
 [6, 0],
 [],
 [],
 [4],
 [],
 [],
 [],
 [],
 [],
 [8],
 [],
 [2],
 [],
 [],
 [],
 [0],
 [1, 17],
 [1],
 [4],
 [0],
 [],
 [2],
 [4],
 [],
 [1],
 [],
 [0],
 [],
 [],
 [],
 [],
 [1],
 [],
 [2],
 [],
 [],
 [8],
 [],
 [],
 [12, 1],
 [0],
 [],
 [],
 [],
 [4],
 [],
 [1],
 [],
 [1, 2],
 [2],
 [4, 1],
 [8],
 [],
 [],
 [],
 [],
 [],
 [],
 [0],
 [6, 0],
 [],
 [8],
 [1],
 [1],
 [],
 [],
 [1],
 [],
 [],
 [],
 [1],
 [],
 [2],
 [1],
 [],
 [2],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [1],
 [0],
 [],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [1],
 [19],
 [],
 [],
 [],
 [2],
 [],
 [],
 [],
 [],
 [2],
 [1],
 [1],
 [2],
 [],
 [1],
 [0],
 [],
 [1],
 [],
 [1],
 [0],
 [1],
 [],
 [1, 4],
 [],
 [],
 [],
 [0],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [2],
 [],
 [1],
 [1],
 [1],
 [],
 [1],
 [2, 1],
 [2],
 [],
 [],
 [1],
 [],
 [1],
 [4],
 [1],
 [],
 [],
 [0],
 [1],
 [],
 [1],
 [],
 [8],
 [],
 [],
 [],
 [],
 [],
 [1],
 [2],
 [1],
 [1],
 [],
 [],
 [8],
 [0],
 [1],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [2],
 [1],
 [1],
 [4],
 [12],
 [0],
 [12],
 [],
 [],
 [],
 [2],
 [2],
 [1],
 [2, 1],
 [],
 [1],
 [1],
 [],
 [2],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [1],
 [1],
 [4],
 [],
 [],
 [1, 2],
 [6, 7],
 [],
 [4, 1],
 [2],
 [],
 [],
 [],
 [4],
 [],
 [2],
 [1],
 [],
 [],
 [0],
 [],
 [],
 [2],
 [],
 [1],
 [],
 [6, 1],
 [],
 [],
 [],
 [1],
 [],
 [],
 [2],
 [0],
 [],
 [],
 [1],
 [],
 [],
 [1, 12],
 [],
 [],
 [],
 [],
 [1],
 [2],
 [1, 2],
 [],
 [],
 [],
 [],
 [],
 [],
 [8],
 [],
 [],
 [],
 [],
 [2],
 [1],
 [4],
 [],
 [],
 [],
 [],
 [4],
 [],
 [],
 [2],
 [],
 [4, 1],
 [1],
 [],
 [],
 [],
 [],
 [],
 [0],
 [],
 [],
 [8],
 [],
 [],
 [1],
 [],
 [13],
 [1],
 [6],
 [4, 0],
 [2],
 [],
 [],
 [],
 [1],
 [1],
 [4],
 [],
 [],
 [2],
 [],
 [0],
 [],
 [1],
 [12],
 [],
 [],
 [],
 [],
 [2],
 [1],
 [1],
 [],
 [1],
 [4],
 [],
 [8],
 [],
 [],
 [],
 [2],
 [1],
 [2],
 [8, 6, 1],
 [],
 [1],
 [1],
 [],
 [],
 [],
 [1, 6],
 ...]

### Build dataset

In [6]:
test_5s_df = pd.DataFrame(columns=dataset_exploration["test_5s"].column_names)

In [7]:
# find all audio files with recordings
audio_files = glob(os.path.join(dataset_root, "audio_annots/*.flac"))

valid_f_audio = []
valid_f_annot = []

skipped_files = []

for audio_file in tqdm(audio_files):
    # find all associated annotation files
    tag_file = audio_file.replace(".flac", "-tags.csv")
    if os.path.exists(tag_file): 
        output_path = audio_file.replace("flac", "ogg")

        # convert all audio files to .ogg
        # try:
        #     audio = AudioSegment.from_file(audio_file)
        #     audio = audio.set_frame_rate(32000).set_channels(1)

        #     audio.export(output_path, format="ogg", codec="libvorbis")

        #     del audio

        # except Exception as e:
        #     print(f"Skipping {audio_file}")
        #     skipped_files.append(audio_file)

        valid_f_audio.append(output_path)
        valid_f_annot.append(tag_file)

  0%|          | 0/2280 [00:00<?, ?it/s]

In [8]:
# concatenate annotation files into .csv appropriate for splitting into 5sec clips
formatted_annots = []
for f in tqdm(valid_f_annot):
    df = pd.read_csv(f)

    df = df[df["tag"] != "UNKN"]

    if df.shape[0] == 0:
        continue

    df.rename(columns={"start": "start_time",
                       "end": "end_time",
                       "frequency_min": "low_f",
                       "frequency_max": "high_f",
                       "tag": "annotation",
                       "file_name": "audio_file"},
                       inplace=True)
        
    df["audio_file"] = df["audio_file"].apply(lambda x: os.path.join(dataset_root, "audio_annots", x))

    df_ebird_class_names = pd.merge(pd.merge(df, dataset_df[["tag", "scientific_name"]], left_on="annotation", right_on="tag"), ebird_df.reset_index(), left_on="scientific_name", right_on="scientific name")["species_code"]
    df["annotation"] = df_ebird_class_names.apply(lambda c: TARGET_CLASSES.index(c) if (not pd.isna(c) and c in TARGET_CLASSES) else pd.NA)

    df.drop(columns=["related", "overlap", "id"], inplace=True)

    formatted_annots.append(df[~df["annotation"].isna()])

df_annots = pd.concat(formatted_annots, ignore_index = True)
df_annots.to_csv(f"/home/gil/comp0173/BirdSet/data/DataS1/boxed_annotations_input_reindexed.csv")

  0%|          | 0/2280 [00:00<?, ?it/s]

In [9]:
df_annots = pd.read_csv("/home/gil/comp0173/BirdSet/data/DataS1/boxed_annotations_input_reindexed.csv", 
                        index_col=0)

annots = BoxedAnnotations(df_annots)
annots.audio_files = annots.df["audio_file"].unique()

In [10]:
df_annots

,audio_file,annotation,start_time,end_time,low_f,high_f
0,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,2.0,12.3034,12.6876,0.0000,1700.0000
1,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,12.0,11.3550,11.8250,2083.3333,3550.0000
2,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,2.0,4.3950,4.6850,150.0000,2916.6667
3,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,2.0,7.7950,7.9750,1183.3333,2883.3333
4,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,2.0,8.1650,8.3450,1250.0000,2916.6667
...,...,...,...,...,...,...
6854,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,11.9250,16.7650,1516.6667,5550.0000
6855,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,17.9450,19.5750,1950.0000,5283.3333
6856,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,0.0350,2.2250,2150.0000,4683.3333
6857,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,12.8850,13.7950,2683.3333,4416.6667
6858,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,16.2350,16.5550,3016.6667,4716.6667

In [11]:
# split audio into five second clips 
boxed_annots, _ = annots.clip_labels(clip_duration=5, clip_overlap=0, min_label_overlap=0.25, class_subset=[i for i in range(len(TARGET_CLASSES))], return_type="classes")

In [12]:
boxed_annots_df = boxed_annots.reset_index()    \
                              .rename(columns={"labels": "ebird_code_multilabel",
                                               "file":"filepath"})

In [17]:
len(TARGET_CLASSES)

31

In [13]:
boxed_annots_df

,filepath,start_time,end_time,ebird_code_multilabel
0,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,0.0,5.0,[]
1,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,5.0,10.0,[]
2,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,10.0,15.0,[2]
3,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,15.0,20.0,[]
4,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,25.0,[]
...,...,...,...,...
6089,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,5.0,10.0,[]
6090,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,10.0,15.0,[20]
6091,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,15.0,20.0,[20]
6092,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,20.0,25.0,[]
6093,/home/gil/comp0173/BirdSet/data/DataS1/audio_a...,25.0,30.0,[]

In [14]:
for col in test_5s_df.columns:
    if col not in boxed_annots_df.columns:
        boxed_annots_df[col] = None

In [15]:
features = dataset_exploration["test_5s"].features.copy()
features["ebird_code_multilabel"]= Sequence(ClassLabel(names=TARGET_CLASSES))

test_5s_dataset = Dataset.from_pandas(boxed_annots_df)   \
                         .cast_column("audio", Audio(sampling_rate=32000, mono=True))   \
                         .cast(features)

Casting the dataset:   0%|          | 0/6094 [00:00<?, ? examples/s]

In [18]:
test_5s_dataset["ebird_code_multilabel"]

[[],
 [],
 [2],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [],
 [],
 [2],
 [2],
 [],
 [],
 [],
 [],
 [21],
 [],
 [],
 [20],
 [20],
 [20],
 [21],
 [21],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20, 21],
 [20],
 [],
 [],
 [],
 [],
 [],
 [18],
 [18],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [7],
 [7],
 [7],
 [7],
 [7],
 [7],
 [20],
 [20],
 [20],
 [20],
 [],
 [12],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [9],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [5, 12],
 [5, 12],
 [5],
 [9],
 [9],
 [9],
 [9],
 [24],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [17],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [29],
 [24, 29],
 [24],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10, 24],
 [],
 [20],
 [],
 [],
 [],
 [],
 [1, 27],
 [1],
 [1, 24],
 [24],
 [24],
 [12, 24],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [5],
 [20],
 [20],
 [20],
 [20],
 [20, 24, 29],
 [29],
 [21],
 [21],
 [21],
 [21],
 [],
 [],
 [10, 24],
 [10, 24],
 [10, 20],
 [10, 20],
 [20],
 [20],
 [12],
 [12, 20],
 [20],
 [20],
 [],
 [],
 [5],
 [5],
 [],
 [12],
 [12],
 [12],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [26],
 [26],
 [24],
 [24],
 [24],
 [24],
 [],
 [2],
 [2],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [21],
 [14, 21],
 [20],
 [20],
 [20],
 [20],
 [],
 [24],
 [24],
 [24],
 [24],
 [24],
 [24],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [24],
 [],
 [],
 [],
 [20],
 [12, 20],
 [20],
 [12, 20],
 [12],
 [],
 [],
 [],
 [],
 [27],
 [27],
 [],
 [7],
 [7],
 [7, 12],
 [12, 20],
 [],
 [],
 [],
 [],
 [],
 [10],
 [],
 [],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [17],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [5],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [5],
 [17],
 [4],
 [17],
 [17],
 [17],
 [17],
 [17],
 [24],
 [10, 24],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [],
 [],
 [10],
 [5, 10],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [2],
 [9],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [10],
 [10, 21],
 [10],
 [],
 [8],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [24],
 [],
 [],
 [],
 [10],
 [10],
 [],
 [29],
 [14, 29],
 [],
 [],
 [],
 [],
 [],
 [21],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [20],
 [],
 [],
 [20],
 [20],
 [20],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [18],
 [],
 [],
 [10],
 [10],
 [8, 10],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [6],
 [],
 [6],
 [20],
 [10, 20],
 [10, 12],
 [5],
 [5],
 [5],
 [5],
 [],
 [],
 [11],
 [11],
 [11],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [14],
 [10, 24],
 [],
 [],
 [20],
 [],
 [],
 [20],
 [],
 [20],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20, 27],
 [20, 27],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [0],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [12],
 [12],
 [],
 [12],
 [],
 [12],
 [12],
 [],
 [],
 [],
 [20],
 [],
 [16],
 [16],
 [],
 [],
 [12],
 [12],
 [12],
 [],
 [12],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [18],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [],
 [],
 [],
 [21],
 [21],
 [1, 10],
 [10],
 [10],
 [10],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [17],
 [20],
 [],
 [20],
 [14],
 [7],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [20],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [12],
 [],
 [],
 [],
 [],
 [1],
 [1],
 [1],
 [],
 [10],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [],
 [],
 [],
 [21],
 [20],
 [20],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [21],
 [],
 [5],
 [],
 [],
 [],
 [],
 [],
 [19],
 [19],
 [5, 19],
 [5, 19],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [12],
 [9],
 [],
 [],
 [10],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [24],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [],
 [],
 [24],
 [],
 [],
 [20, 21],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20, 21],
 [20],
 [],
 [],
 [],
 [12],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [5],
 [5],
 [5],
 [5, 21],
 [21],
 [],
 [27],
 [],
 [24],
 [],
 [],
 [],
 [21],
 [4],
 [4],
 [4],
 [4],
 [],
 [],
 [],
 [],
 [],
 [],
 [22],
 [],
 [],
 [],
 [],
 [20, 21],
 [],
 [29],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [5],
 [],
 [],
 [5, 8],
 [8],
 [8, 21],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [11],
 [11],
 [11],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20],
 [20],
 [8],
 [20],
 [20],
 [],
 [8],
 [],
 [],
 [12],
 [],
 [],
 [],
 [12],
 [12],
 [],
 [7],
 [7],
 [7],
 [],
 [],
 [24],
 [24],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [12],
 [12],
 [],
 [20],
 [20],
 [],
 [20],
 [20],
 [20],
 [13],
 [13],
 [],
 [13],
 [13],
 [13],
 [12],
 [12],
 [1],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [24],
 [24],
 [9],
 [9],
 [9],
 [9],
 [5, 24],
 [5],
 [5],
 [],
 [],
 [5],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [20],
 [20],
 [20, 21],
 [21],
 [5, 21],
 [20],
 [20],
 [],
 [20],
 [20],
 [],
 [12],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [5],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [15],
 [15],
 [15],
 [15],
 [5],
 [],
 [],
 [],
 [],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [],
 [5],
 [],
 [],
 [],
 [20],
 [20],
 [12],
 [],
 [],
 [],
 [],
 [21],
 [21],
 [21],
 [21],
 [],
 [5, 24],
 [17],
 [17],
 [17],
 [17],
 [17],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [],
 [23],
 [23],
 [23],
 [23],
 [23],
 [23],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [12, 20],
 [20],
 [20],
 [20],
 [20],
 [20, 21],
 [],
 [],
 [4],
 [4],
 [4],
 [4, 17],
 [],
 ...]

In [19]:
test_5s_dataset.to_parquet("/home/gil/comp0173/BirdSet/data/DataS1/metadata.jsonl")

Creating parquet from Arrow format:   0%|          | 0/61 [00:00<?, ?ba/s]

1572086

In [20]:
test_5s_dataset = load_dataset("parquet", data_files="/home/gil/comp0173/BirdSet/data/DataS1/metadata.jsonl")["train"]

Generating train split: 0 examples [00:00, ? examples/s]

In [22]:
test_5s_dataset["ebird_code_multilabel"]

[[],
 [],
 [2],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [],
 [],
 [2],
 [2],
 [],
 [],
 [],
 [],
 [21],
 [],
 [],
 [20],
 [20],
 [20],
 [21],
 [21],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20, 21],
 [20],
 [],
 [],
 [],
 [],
 [],
 [18],
 [18],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [7],
 [7],
 [7],
 [7],
 [7],
 [7],
 [20],
 [20],
 [20],
 [20],
 [],
 [12],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [9],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [5, 12],
 [5, 12],
 [5],
 [9],
 [9],
 [9],
 [9],
 [24],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [17],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [29],
 [24, 29],
 [24],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10, 24],
 [],
 [20],
 [],
 [],
 [],
 [],
 [1, 27],
 [1],
 [1, 24],
 [24],
 [24],
 [12, 24],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [5],
 [20],
 [20],
 [20],
 [20],
 [20, 24, 29],
 [29],
 [21],
 [21],
 [21],
 [21],
 [],
 [],
 [10, 24],
 [10, 24],
 [10, 20],
 [10, 20],
 [20],
 [20],
 [12],
 [12, 20],
 [20],
 [20],
 [],
 [],
 [5],
 [5],
 [],
 [12],
 [12],
 [12],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [26],
 [26],
 [24],
 [24],
 [24],
 [24],
 [],
 [2],
 [2],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [21],
 [14, 21],
 [20],
 [20],
 [20],
 [20],
 [],
 [24],
 [24],
 [24],
 [24],
 [24],
 [24],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [24],
 [],
 [],
 [],
 [20],
 [12, 20],
 [20],
 [12, 20],
 [12],
 [],
 [],
 [],
 [],
 [27],
 [27],
 [],
 [7],
 [7],
 [7, 12],
 [12, 20],
 [],
 [],
 [],
 [],
 [],
 [10],
 [],
 [],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [17],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [5],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [5],
 [17],
 [4],
 [17],
 [17],
 [17],
 [17],
 [17],
 [24],
 [10, 24],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [],
 [],
 [10],
 [5, 10],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [2],
 [9],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [10],
 [10, 21],
 [10],
 [],
 [8],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [24],
 [],
 [],
 [],
 [10],
 [10],
 [],
 [29],
 [14, 29],
 [],
 [],
 [],
 [],
 [],
 [21],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [20],
 [],
 [],
 [20],
 [20],
 [20],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [18],
 [],
 [],
 [10],
 [10],
 [8, 10],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [6],
 [],
 [6],
 [20],
 [10, 20],
 [10, 12],
 [5],
 [5],
 [5],
 [5],
 [],
 [],
 [11],
 [11],
 [11],
 [],
 [],
 [],
 [1],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [14],
 [10, 24],
 [],
 [],
 [20],
 [],
 [],
 [20],
 [],
 [20],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20, 27],
 [20, 27],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [5],
 [],
 [],
 [],
 [],
 [],
 [],
 [0],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [12],
 [12],
 [],
 [12],
 [],
 [12],
 [12],
 [],
 [],
 [],
 [20],
 [],
 [16],
 [16],
 [],
 [],
 [12],
 [12],
 [12],
 [],
 [12],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [18],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [],
 [],
 [],
 [21],
 [21],
 [1, 10],
 [10],
 [10],
 [10],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [],
 [10],
 [10],
 [10],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [17],
 [20],
 [],
 [20],
 [14],
 [7],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [20],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [12],
 [],
 [],
 [],
 [],
 [1],
 [1],
 [1],
 [],
 [10],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [],
 [],
 [],
 [21],
 [20],
 [20],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [21],
 [],
 [5],
 [],
 [],
 [],
 [],
 [],
 [19],
 [19],
 [5, 19],
 [5, 19],
 [12],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [12],
 [9],
 [],
 [],
 [10],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [24],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [],
 [],
 [24],
 [],
 [],
 [20, 21],
 [21],
 [21],
 [21],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20, 21],
 [20],
 [],
 [],
 [],
 [12],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [5],
 [5],
 [5],
 [5, 21],
 [21],
 [],
 [27],
 [],
 [24],
 [],
 [],
 [],
 [21],
 [4],
 [4],
 [4],
 [4],
 [],
 [],
 [],
 [],
 [],
 [],
 [22],
 [],
 [],
 [],
 [],
 [20, 21],
 [],
 [29],
 [],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [5],
 [],
 [],
 [5, 8],
 [8],
 [8, 21],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [11],
 [11],
 [11],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [20],
 [20],
 [8],
 [20],
 [20],
 [],
 [8],
 [],
 [],
 [12],
 [],
 [],
 [],
 [12],
 [12],
 [],
 [7],
 [7],
 [7],
 [],
 [],
 [24],
 [24],
 [],
 [],
 [],
 [],
 [],
 [12],
 [],
 [12],
 [12],
 [],
 [20],
 [20],
 [],
 [20],
 [20],
 [20],
 [13],
 [13],
 [],
 [13],
 [13],
 [13],
 [12],
 [12],
 [1],
 [],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [24],
 [24],
 [9],
 [9],
 [9],
 [9],
 [5, 24],
 [5],
 [5],
 [],
 [],
 [5],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [20],
 [20],
 [20, 21],
 [21],
 [5, 21],
 [20],
 [20],
 [],
 [20],
 [20],
 [],
 [12],
 [],
 [],
 [],
 [12],
 [12],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [10],
 [10],
 [10],
 [],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [5],
 [],
 [],
 [20],
 [20],
 [],
 [],
 [],
 [],
 [],
 [15],
 [15],
 [15],
 [15],
 [5],
 [],
 [],
 [],
 [],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [5],
 [],
 [5],
 [],
 [],
 [],
 [20],
 [20],
 [12],
 [],
 [],
 [],
 [],
 [21],
 [21],
 [21],
 [21],
 [],
 [5, 24],
 [17],
 [17],
 [17],
 [17],
 [17],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [20],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [10],
 [],
 [23],
 [23],
 [23],
 [23],
 [23],
 [23],
 [],
 [],
 [20],
 [20],
 [20],
 [20],
 [12, 20],
 [20],
 [20],
 [20],
 [20],
 [20, 21],
 [],
 [],
 [4],
 [4],
 [4],
 [4, 17],
 [],
 ...]

## Join Datasets

In [3]:
dataset_DT_train = load_dataset("parquet", data_files="/home/gil/comp0173/BirdSet/data/DataS1_DT_train/metadata-train.parquet")["train"]
test_5s_dataset = load_dataset("parquet", data_files="/home/gil/comp0173/BirdSet/data/DataS1/metadata.parquet")["train"]

dataset_DT_train = dataset_DT_train.cast_column("audio", Audio(sampling_rate=32000, mono=True))
test_5s_dataset = test_5s_dataset.cast_column("audio", Audio(sampling_rate=32000, mono=True))

joined_dataset = DatasetDict({"train": dataset_DT_train,
                              "test_5s": test_5s_dataset
                              })

In [5]:
dataset_DT_train.features

{'filepath': Value(dtype='string', id=None),
 'start_time': Value(dtype='null', id=None),
 'end_time': Value(dtype='null', id=None),
 'low_freq': Value(dtype='null', id=None),
 'high_freq': Value(dtype='null', id=None),
 'lat': Value(dtype='float64', id=None),
 'long': Value(dtype='float64', id=None),
 'length': Value(dtype='int64', id=None),
 'call_type': Value(dtype='string', id=None),
 'sex': Value(dtype='string', id=None),
 'licence': Value(dtype='string', id=None),
 'local_time': Value(dtype='string', id=None),
 'ebird_code': Value(dtype='int64', id=None),
 'ebird_code_multilabel': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None),
 'ebird_code_secondary': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None),
 'quality': Value(dtype='string', id=None),
 'microphone': Value(dtype='string', id=None),
 'source': Value(dtype='string', id=None),
 'detected_events': Sequence(feature=Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None), length=-1, id=None),
 'event_cluster': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None),
 'recordist': Value(dtype='string', id=None),
 'peaks': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None),
 'license': Value(dtype='string', id=None),
 'order': Value(dtype='string', id=None),
 'species_group': Value(dtype='string', id=None),
 'genus': Value(dtype='string', id=None),
 'audio': Audio(sampling_rate=32000, mono=True, decode=True, id=None),
 'id': Value(dtype='int64', id=None)}

In [4]:
test_5s_dataset.features

{'audio': Audio(sampling_rate=32000, mono=True, decode=True, id=None),
 'filepath': Value(dtype='string', id=None),
 'start_time': Value(dtype='float64', id=None),
 'end_time': Value(dtype='float64', id=None),
 'low_freq': Value(dtype='int64', id=None),
 'high_freq': Value(dtype='int64', id=None),
 'ebird_code': ClassLabel(names=['gcrfin', 'whcspa', 'amepip', 'sposan', 'rocwre', 'brebla', 'daejun', 'foxspa', 'clanut', 'moublu', 'casfin', 'mallar3', 'herthr', 'amerob', 'yerwar', 'yelwar', 'dusfly', 'mouchi', 'orcwar', 'warvir', 'norfli'], id=None),
 'ebird_code_multilabel': Sequence(feature=ClassLabel(names=['snogoo', 'pecsan', 'amgplo', 'batgod', 'cangoo', 'brant', 'gwfgoo', 'pursan', 'speeid', 'lotduc', 'pacloo', 'snobun', 'lotjae', 'dunlin', 'whrsan', 'tunswa', 'arcter', 'rudtur', 'lobdow', 'retloo', 'laplon', 'semsan', 'bkbplo', 'baisan', 'kineid', 'pomjae', 'sabgul', 'redpha1', 'sander', 'comrav', 'semplo'], id=None), length=-1, id=None),
 'ebird_code_secondary': Sequence(feature=Value(dtype='string', id=None), length=-1, id=None),
 'call_type': Value(dtype='string', id=None),
 'sex': Value(dtype='string', id=None),
 'lat': Value(dtype='float64', id=None),
 'long': Value(dtype='float64', id=None),
 'length': Value(dtype='int64', id=None),
 'microphone': Value(dtype='string', id=None),
 'license': Value(dtype='string', id=None),
 'source': Value(dtype='string', id=None),
 'local_time': Value(dtype='string', id=None),
 'detected_events': Sequence(feature=Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None), length=-1, id=None),
 'event_cluster': Sequence(feature=Value(dtype='int64', id=None), length=-1, id=None),
 'peaks': Sequence(feature=Value(dtype='float64', id=None), length=-1, id=None),
 'quality': Value(dtype='string', id=None),
 'recordist': Value(dtype='string', id=None),
 'genus': ClassLabel(names=['actitis', 'anas', 'anthus', 'catharus', 'colaptes', 'empidonax', 'euphagus', 'haemorhous', 'junco', 'leiothlypis', 'leucosticte', 'nucifraga', 'passerella', 'poecile', 'salpinctes', 'setophaga', 'sialia', 'turdus', 'vireo', 'zonotrichia'], id=None),
 'species_group': ClassLabel(names=['blackbirds', 'finches, euphonias, and allies', 'jays, magpies, crows, and ravens', 'new world sparrows', 'shorebirds', 'thrushes', 'tits, chickadees, and titmice', 'tyrant flycatchers: pewees, kingbirds, and allies', 'vireos', 'wagtails and pipits', 'waterfowl', 'wood-warblers', 'woodpeckers', 'wrens'], id=None),
 'order': ClassLabel(names=['anseriformes', 'charadriiformes', 'passeriformes', 'piciformes'], id=None),
 'genus_multilabel': Sequence(feature=ClassLabel(names=['actitis', 'anas', 'anthus', 'catharus', 'colaptes', 'empidonax', 'euphagus', 'haemorhous', 'junco', 'leiothlypis', 'leucosticte', 'nucifraga', 'passerella', 'poecile', 'salpinctes', 'setophaga', 'sialia', 'turdus', 'vireo', 'zonotrichia'], id=None), length=-1, id=None),
 'species_group_multilabel': Sequence(feature=ClassLabel(names=['blackbirds', 'finches, euphonias, and allies', 'jays, magpies, crows, and ravens', 'new world sparrows', 'shorebirds', 'thrushes', 'tits, chickadees, and titmice', 'tyrant flycatchers: pewees, kingbirds, and allies', 'vireos', 'wagtails and pipits', 'waterfowl', 'wood-warblers', 'woodpeckers', 'wrens'], id=None), length=-1, id=None),
 'order_multilabel': Sequence(feature=ClassLabel(names=['anseriformes', 'charadriiformes', 'passeriformes', 'piciformes'], id=None), length=-1, id=None)}